export const EDIT_DATA = 'EDIT_DATA'

export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const LOAD_MAHASISWA_SUCCESS = 'LOAD_MAHASISWA_SUCCESS'
export const LOAD_MATAKULIAH_SUCCESS = 'LOAD_MATAKULIAH_SUCCESS'